FreightMana/Controllers/ConfirmController.cs
using FreightMana.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FreightMana.Controllers
{
    public class ConfirmController : Controller
    {
        ManaFreightmentContext db = new ManaFreightmentContext();
        private static List<Order> orders;
        public IActionResult Index()
        {
            orders = new List<Order>() { };
            orders = db.Orders
            .Where(o => o.Status == "Chờ xác nhận")
            .Include(o => o.Receiver)
            .Include(o => o.Transport)
            .ToList();
            
            return View(orders);
        }
        [HttpPost]
        public IActionResult Confirm(List<String> statusList)
        {
           // List<Order> list = db.Orders.Where(o => o.Status == "Chờ xác nhận"  ).ToList();
            if(orders.Count == statusList.Count)
            {
                for (int i = 0; i < orders.Count; i++)
                {
                    var order = db.Orders.Find(orders[i].OrderId);
                   order.Status = statusList[i];
                    order.ConfirmAt = DateTime.Now;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Search(string keyword)
        {
            System.Diagnostics.Debug.WriteLine("searching");
            orders = db.Orders.Where(o =>
                (o.OrderId.ToString().Contains(keyword) ||
                o.Receiver.Name.Contains(keyword) ||
                o.Receiver.PhoneNumber.Contains(keyword) ||
                o.Receiver.Address.Contains(keyword) ||
                o.Status.Contains(keyword)) &&
                o.Status == "Chờ xác nhận"
            )
                .Include(o => o.Receiver)
                .Include(o => o.Transport)
                .ToList();

            return View("Index", orders);
        }

        public IActionResult DeleteOrder(int orderId)
        {
            var order = db.Orders.Find(orderId);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FreightMana/Controllers/CreateGoodsController.cs
using FreightMana.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Text.Json;
using System.Text;
using System.Collections.Generic;

namespace FreightMana.Controllers
{
    [Route("excel")]
    public class CreateGoodsController : Controller
    {
        private static List<Order> listOrder = new List<Order>();

        ManaFreightmentContext db = new ManaFreightmentContext();
        public IActionResult Index()
        {
            System.Diagnostics.Debug.WriteLine(listOrder.Count);
            return View( listOrder);
        }
        [HttpPost("upload")]
        public IActionResult ReadExcelFile(IFormFile excelFile)
        {
            //List <Order> listOrder = new List<Order>();
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            if (excelFile != null && excelFile.Length > 0)
            {
                using (var stream = new MemoryStream())
                {
                    excelFile.CopyTo(stream);
                    using (var package = new ExcelPackage(stream)) //Tạo đối tượng chứa dữ liệu của file excel
                    {
                        var worksheet = package.Workbook.Worksheets[0]; //Lấy ra sheet đầu tiên
                        var rowCount = worksheet.Dimension.Rows; //Tính toán số dòng

                        for (int row = 3; row <= rowCount; row++) //Duyệt từng dòng và lấy dữ liệu
                        {
                            try { 
                            //Tên sp 
                                var productName = worksheet.Cells[row, 1].Value?.ToString();
                                //Số lượng
                                var numOfProduct = int.Parse(worksheet.Cells[row, 2].Value?.ToString());
                                //Mã vận chuyển
                                var transportId = int.Parse(worksheet.Cells[row, 3].Value?.ToString());
                                //COD
                                var cod = float.Parse(worksheet.Cells[row, 4].Value?.ToString());
                                //Phí vận chuyển
                                var fee = float.Parse(worksheet.Cells[row, 5].Value?.ToString());
                                //Note
                                var note = worksheet.Cells[row, 6].Value?.ToString();
                                //Tên người gửi
                                var senderName = worksheet.Cells[row, 7].Value?.ToString();
                                //Số điện thoại người gửi
                                var senderPhone = worksheet.Cells[row, 8].Value?.ToString();
                                //Địa chỉ người gửi
                                var senderAddress = worksheet.Cells[row, 9].Value?.ToString();
                                //Tên người nhận
                                var recName = worksheet.Cells[row, 10].Value?.ToString();
                                //Số điện thoại người nhận
                                var recPhone = worksheet.Cells[row, 11].Value?.ToString();
                                //Địa chỉ người nhận
                                var recAddress = worksheet.Cells[row, 12].Value?.ToString();
                                //Thêm người gửi
                                Sender sender = new Sender() { 
                                    Name = senderName,
                                    PhoneNumber = senderPhone,
                                    Address = senderAddress,
                                };
                                
                                //db.Senders.RemoveRange(db.Senders.Where(r => r.Name == sender.Name));
                                db.Senders.Add(sender);
                                //db.SaveChanges();
                                //Thêm người nhận
                                Receiver receiver = new Receiver()
                                {
                                    Name = recName,
                                    PhoneNumber = recPhone,
                                    Address = recAddress
                                };

                               
                                //db.Receivers.RemoveRange(db.Receivers.Where(r => r.Name == receiver.Name));
                                db.Receivers.Add(receiver);
                                db.SaveChanges();
                                //System.Diagnostics.Debug.WriteLine(receiver.Address);
                                //Thêm đơn hàng
                                Order order = new Order()
                                {
                                    Product = productName,
                                    NumberOfProduct = numOfProduct,
                                    TransportId = transportId,
                                    Cod = cod,
                                    TransportFee = fee,
                                    Note = note,
                                    SenderId = sender.Id,
                                    ReceiverId = receiver.Id,
                                    RecordAt = DateTime.Now,
                                    WarehouseId = 1,
                                    Status = "Chờ xác nhận"
                                };
                                //System.Diagnostics.Debug.WriteLine(order.SenderId);
                                //db.Orders.RemoveRange(db.Orders.Where(o => o.Product == order.Product));                              
                                db.Orders.Add(order);
                                db.SaveChanges();
                                listOrder.Add(order);
                                TempData["message"] = "Thêm đơn thành công";
                            }
                            catch (Exception e)
                            {
                                TempData["message"] = e.ToString();
                                return RedirectToAction("Index");
                            }
                        }
                    }
                }
              
            }
           
            return RedirectToAction("Index");
        }
    }
}

FreightMana/Controllers/StaffController.cs
using FreightMana.Models;
using Microsoft.AspNetCore.Mvc;

namespace FreightMana.Controllers
{
    public class StaffController : Controller
    {
        ManaFreightmentContext db = new ManaFreightmentContext();
        public IActionResult Index()
        {
            var listStaff = db.Staffs.ToList();
            ViewBag.staffList = listStaff;
            return View();
        }
        public ActionResult Confirm(Staff staff)
        {
            staff.WarehouseId = 1;
            db.Staffs.Add(staff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Staff staff = db.Staffs.FirstOrDefault(s => s.Id == id);
            db.Staffs.Remove(staff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult editStaff(int id)
        {
            var eStaff = db.Staffs.FirstOrDefault(s=>s.Id == id);
            return View(eStaff);
        }
        [HttpPost]

        public ActionResult ConfirmEdit(Staff staff)
        {   
            Staff sf = db.Staffs.FirstOrDefault(s => s.Id == staff.Id);
            sf.Id = staff.Id;
            sf.Position = staff.Position;
            sf.Name = staff.Name;
            sf.PhoneNumber = staff.PhoneNumber;
            sf.Email = staff.Email;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FreightMana/Controllers/TimeWorkController.cs
using FreightMana.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FreightMana.Controllers
{
    public class TimeWorkController : Controller
    {
        ManaFreightmentContext db = new ManaFreightmentContext();
        public IActionResult Index()
        {
            var staffs = db.Staffs.ToList();
            ViewBag.Staffs = staffs;
            var shifts = db.Shifts.Include(e => e.Employee).OrderByDescending(e => e.Day).ToList();
            return View(shifts);
        }
        public IActionResult CreateShift(int staffId, String timeRange)
        {
            TimeOnly timeStart, timeEnd;
            switch (timeRange)
            {
                case "morning":
                    timeStart = new TimeOnly(7, 0);
                    timeEnd = new TimeOnly(11, 0);
                    break;
                case "afternoon":
                    timeStart = new TimeOnly(12, 0);
                    timeEnd = new TimeOnly(17, 0);
                    break;
                case "evening":
                    timeStart = new TimeOnly(18, 0);
                    timeEnd = new TimeOnly(22, 0);
                    break;
                default:
                    timeStart = new TimeOnly(7, 0);
                    timeEnd = new TimeOnly(11, 0);
                    break;
            }
            var shiftsOfDay = db.Shifts.Where(s => s.EmployeeId == staffId && s.Day == DateOnly.FromDateTime(DateTime.Now)).ToList();
            bool shiftConflict = shiftsOfDay.Any(s => (s.TimeStart < timeEnd && s.TimeEnd > timeStart));

            if (shiftConflict)
            {
                TempData["ErrorMessage"] = "Trùng ca làm trong ngày!";
                return RedirectToAction("Index");
            }

            db.Shifts.Add(new Shift()
            {
                Day = DateOnly.FromDateTime(DateTime.Now),
                EmployeeId = staffId,
                TimeStart = timeStart,
                TimeEnd = timeEnd,
            });
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult DeleteShift(int id)
        {
            db.Shifts.Remove(db.Shifts.FirstOrDefault(s => s.Id == id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

FreightMana/Views/CreateGoods/Index.cshtml
@model List<Order>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/img/fevicon.png" type="image/x-icon">
    <title>CREATE GOODS</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="~/css/base.css">
    <link rel="stylesheet" href="~/css/Admin/sidebar.css">
    <link rel="stylesheet" href="~/css/Admin/create_goods.css">
</head>
<body>
    <nav class="sidebar">
        <div class="logo">
            <a href=""><img src="~/img/logo.png" alt=""></a>
        </div>
        <ul id="sidebar_menu" class="metismenu">
            <li>
                <a href="@Url.Action("Index", "Dashboard")" style="background-color: var(--light-color);width: 215px;"><span><i class="fa-solid fa-house"></i>Thống kê</span></a>
            </li>
            <li>
                <a href="@Url.Action("Index", "ListOrder")"><span><i class="fa-solid fa-list-ul"></i>Danh sách đơn hàng</span></a>
            </li>

            <button class="toggleButton" onclick="order_Menu()"><span style="font-size: 16px; color: var(--grey-color);"><i class="fa-regular fa-folder"></i>Tạo đơn</span></button>

            <ul class="menu">
                <li><a href="@Url.Action("Index", "CreateOrder")"><span><i class="fa-regular fa-file-lines"></i>Đơn lẻ</span></a></li>
                <li><a href="@Url.Action("Index", "CreateGoods")"><span><i class="fa-regular fa-file-excel"></i>Đơn hàng loạt</span></a></li>
            </ul>
            <li>
                <a href="@Url.Action("Index", "Confirm")"><span><i class="fa-regular fa-folder-closed"></i>Xác nhận đơn hàng</span></a>
            </li>
            <button class="toggleButton" onclick="staff_Menu()"><span style="font-size: 16px; color: var(--grey-color);"><i class="fa-regular fa-folder"></i>Nhân viên</span></button>

            <ul class="staff">
                <li><a href="@Url.Action("Index", "Staff")"><span><i class="fa-regular fa-file-lines"></i>Thông tin cá nhân</span></a></li>
                <li><a href="@Url.Action("Index", "TimeWork")"><span><i class="fa-regular fa-file-excel"></i>Ca làm việc</span></a></li>
            </ul>

        </ul>
    </nav>
    <nav class="main">
        <div class="nav-bar">
            <div class="infor">
                <div class="avt">
                    <a href=""><img src="~/img/avt.jpg" alt=""></a>
                </div>
                <div class="name">
                    <span>Admin</span>
                </div>
                <div class="log-out">
                    <div id="myLogout" class="logout-content">
                        <a href="#" onclick="return confirmLogout()"><span>Đăng xuất </span><i class="fa-solid fa-right-from-bracket" style="color: var(--turquoise-color);"></i></a>
                    </div>
                </div>
            </div>
        </div>
        

        <script>
            function uploadFile() {
                var fileInput = document.getElementById('customFileInput');
                var file = fileInput.files[0];

                if (file) {
                    document.getElementById('mform').submit();
                } else {
                    alert('Vui lòng chọn một file Excel để tải lên!');
                }
            }
           
                function displayFileName(input) {
                    var selectedFileName = document.getElementById('selectedFileName');
                    if (input.files.length > 0) {
                        selectedFileName.textContent = input.files[0].name;
                    } else {
                        selectedFileName.textContent = '';
                    }

                }
        </script>
        <div class="upload">
           
            <style>
                #customFileInput {
                    font-size:14px;
                    width: 0.1px;
                    height: 0.1px;
                    opacity: 0;
                    overflow: hidden;
                    position: absolute;
                    z-index: -1;
                }

                #customFileLabel {
                    box-shadow: 2px 2px 2px grey;
                    font-size: 14px;
                    display: inline-block;
                    padding: 8px 12px;
                    background-color: #4ba3f0;
                    color: #fff;
                    border-radius: 5px;
                    cursor: pointer;
                }

                #selectedFileName{
                    width:200px;
                    margin-left:15px;
                    margin-top:10px;
                    overflow:hidden;
                }
            </style>
            @{
                if (ViewBag.Noti != null)
                {
                    <script>
                        alert('@ViewBag.Noti');
                    </script>
                }
                if (TempData["message"] != null)
                {
                
                    <script>
                        alert('@Html.Raw(TempData["message"])');
                    </script>
                }
            }
            <form action="/excel/upload" method="post" enctype="multipart/form-data" id="mform">
           
             
            <div class="upload-file">
                    <input type="file" id="customFileInput" onchange="displayFileName(this)" accept=".xlsx, .xls" name="excelFile">
                    <label for="customFileInput" id="customFileLabel">Chọn file Excel</label>
                    <span id="selectedFileName"></span>      
                    <input type="button" value="Tải file mẫu" onclick="uploadFile()">
				
			</div></form>
            
        </div>
        <div class="goods-backgr">
            <table>
                <tr>
                    <th style="width: 280px; text-align: left;">Người nhận</th>
                    <th style="width: 850px; text-align: left;">Địa chỉ nhận</th>
                    <th>Cước phí</th>
                    <th>COD</th>
                    <th></th>
                </tr>
                @if (Model.Count!= 0 )
                {
                    foreach (var order in Model)
                    {
                        <tr>
                            <td>@order.Receiver.Name</td>
                            <td>@order.Receiver.Address</td>
                            <td>@order.TransportFee</td>
                            <td>@order.Cod</td>
                            
                        </tr>
                    }
                }
           
                
                
            </table>
        </div>
    </nav>

    <script src="~/js/sidebar.js"></script>
</body>
</html>