FreightMana/Controllers/ConfirmController.cs
using FreightMana.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FreightMana.Controllers
{
    public class ConfirmController : Controller
    {
        ManaFreightmentContext db = new ManaFreightmentContext();
        private static List<Order> orders;
        public IActionResult Index()
        {
            orders = new List<Order>() { };
            orders = db.Orders
            .Where(o => o.Status == "Chờ xác nhận")
            .Include(o => o.Receiver)
            .Include(o => o.Transport)
            .ToList();
            
            return View(orders);
        }
        [HttpPost]
        public IActionResult Confirm(List<String> statusList)
        {
           // List<Order> list = db.Orders.Where(o => o.Status == "Chờ xác nhận"  ).ToList();
            if(orders.Count == statusList.Count)
            {
                for (int i = 0; i < orders.Count; i++)
                {
                    var order = db.Orders.Find(orders[i].OrderId);
                   order.Status = statusList[i];
                    order.ConfirmAt = DateTime.Now;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Search(string keyword)
        {
            System.Diagnostics.Debug.WriteLine("searching");
            orders = db.Orders.Where(o =>
                (o.OrderId.ToString().Contains(keyword) ||
                o.Receiver.Name.Contains(keyword) ||
                o.Receiver.PhoneNumber.Contains(keyword) ||
                o.Receiver.Address.Contains(keyword) ||
                o.Status.Contains(keyword)) &&
                o.Status == "Chờ xác nhận"
            )
                .Include(o => o.Receiver)
                .Include(o => o.Transport)
                .ToList();

            return View("Index", orders);
        }

        public IActionResult DeleteOrder(int orderId)
        {
            var order = db.Orders.Find(orderId);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FreightMana/Controllers/DashboardController.cs
using FreightMana.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FreightMana.Controllers
{
	public class DashboardController : Controller
    {
		ManaFreightmentContext db = new ManaFreightmentContext();
      //  [Authorize]
        public IActionResult Index()
        {
			var totalRevenue = db.Orders.Where(o => o.Status != "Chờ xác nhận").Sum(o => o.TransportFee);
			ViewBag.TotalRevenue = totalRevenue;

			// Tính tổng số đơn hàng
			int totalOrders = db.Orders.Where(o => o.Status != "Chờ xác nhận").Count();
			ViewBag.TotalOrders = totalOrders;

			// Tính tổng số đơn hàng đã giao
			int deliveredOrders = db.Orders.Count(o => o.Status == "Đã hoàn thành");
			ViewBag.DeliveredOrders = deliveredOrders;

			// Tính tổng số đơn hàng đã hủy
			int cancelledOrders = db.Orders.Count(o => o.Status == "Đã hủy");
			ViewBag.CancelledOrders = cancelledOrders;

			// Tính tổng số đơn hàng chưa giao
			int pendingOrders = db.Orders.Count(o => o.Status != "Đã hoàn thành" && o.Status != "Đã hủy" && o.Status != "Chờ xác nhận");
			ViewBag.PendingOrders = pendingOrders;

            // list all
            var allOrders = db.Orders
           .Select(o => new
           {
               o.Receiver.Name,
               o.Receiver.Address,
               o.Receiver.PhoneNumber,
               o.OrderId,
               o.Cod,
               o.Transport.Cost,
               o.Status,
               o.ConfirmAt
           })
           .Where(o=>o.Status!="Chờ xác nhận")
           .ToList();
            ViewBag.AllOrders = allOrders;

            // list đơn chưa giao
            var shippingOrders = db.Orders
              .Where(o=> o.Status == "Đang giao hàng")
              .Select(o => new
              {
                  o.Receiver.Name,
                  o.Receiver.Address,
                  o.Receiver.PhoneNumber,
                  o.OrderId,
                  o.Cod,
                  o.Transport.Cost,
                  o.Status,
                  o.ConfirmAt
              })
              .ToList();
            ViewBag.ShippingOrders = shippingOrders;

            //list đơn hoàn thành
            var completedOrders = db.Orders
              .Where(o => o.Status == "Đã hoàn thành")
              .Select(o => new
              {
                  o.Receiver.Name,
                  o.Receiver.Address,
                  o.Receiver.PhoneNumber,
                  o.OrderId,
                  o.Cod,
                  o.Transport.Cost,
                  o.Status,
                  o.CompleteAt
              })
              .ToList();
            ViewBag.CompletedOrders = completedOrders;

            //list đơn đã hủy
            var cancelOrders = db.Orders
              .Where(o => o.Status == "Đã hủy")
              .Select(o => new
              {
                  o.Receiver.Name,
                  o.Receiver.Address,
                  o.Receiver.PhoneNumber,
                  o.OrderId,
                  o.Cod,
                  o.Transport.Cost,
                  o.Status,
                  o.CancelAt
              })
              .ToList();
            ViewBag.CancelOrders = cancelOrders;
            return View();
        }
    }
}

FreightMana/Controllers/StaffController.cs
using FreightMana.Models;
using Microsoft.AspNetCore.Mvc;

namespace FreightMana.Controllers
{
    public class StaffController : Controller
    {
        ManaFreightmentContext db = new ManaFreightmentContext();
        public IActionResult Index()
        {
            var listStaff = db.Staffs.ToList();
            ViewBag.staffList = listStaff;
            return View();
        }
        public ActionResult Confirm(Staff staff)
        {
            staff.WarehouseId = 1;
            db.Staffs.Add(staff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Staff staff = db.Staffs.FirstOrDefault(s => s.Id == id);
            db.Staffs.Remove(staff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult editStaff(int id)
        {
            var eStaff = db.Staffs.FirstOrDefault(s=>s.Id == id);
            return View(eStaff);
        }
        [HttpPost]

        public ActionResult ConfirmEdit(Staff staff)
        {   
            Staff sf = db.Staffs.FirstOrDefault(s => s.Id == staff.Id);
            sf.Id = staff.Id;
            sf.Position = staff.Position;
            sf.Name = staff.Name;
            sf.PhoneNumber = staff.PhoneNumber;
            sf.Email = staff.Email;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FreightMana/Controllers/TimeWorkController.cs
using FreightMana.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FreightMana.Controllers
{
    public class TimeWorkController : Controller
    {
        ManaFreightmentContext db = new ManaFreightmentContext();
        public IActionResult Index()
        {
            var staffs = db.Staffs.ToList();
            ViewBag.Staffs = staffs;
            var shifts = db.Shifts.Include(e => e.Employee).OrderByDescending(e => e.Day).ToList();
            return View(shifts);
        }
        public IActionResult CreateShift(int staffId, String timeRange)
        {
            TimeOnly timeStart, timeEnd;
            switch (timeRange)
            {
                case "morning":
                    timeStart = new TimeOnly(7, 0);
                    timeEnd = new TimeOnly(11, 0);
                    break;
                case "afternoon":
                    timeStart = new TimeOnly(12, 0);
                    timeEnd = new TimeOnly(17, 0);
                    break;
                case "evening":
                    timeStart = new TimeOnly(18, 0);
                    timeEnd = new TimeOnly(22, 0);
                    break;
                default:
                    timeStart = new TimeOnly(7, 0);
                    timeEnd = new TimeOnly(11, 0);
                    break;
            }
            var shiftsOfDay = db.Shifts.Where(s => s.EmployeeId == staffId && s.Day == DateOnly.FromDateTime(DateTime.Now)).ToList();
            bool shiftConflict = shiftsOfDay.Any(s => (s.TimeStart < timeEnd && s.TimeEnd > timeStart));

            if (shiftConflict)
            {
                TempData["ErrorMessage"] = "Trùng ca làm trong ngày!";
                return RedirectToAction("Index");
            }

            db.Shifts.Add(new Shift()
            {
                Day = DateOnly.FromDateTime(DateTime.Now),
                EmployeeId = staffId,
                TimeStart = timeStart,
                TimeEnd = timeEnd,
            });
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult DeleteShift(int id)
        {
            db.Shifts.Remove(db.Shifts.FirstOrDefault(s => s.Id == id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

FreightMana/Views/TimeWork/Index.cshtml
@model List<Shift>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TIME WORK</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="icon" href="~/img/fevicon.png" type="image/x-icon">
    <link rel="stylesheet" href="~/css/base.css">
    <link rel="stylesheet" href="~/css/Admin/sidebar.css">
    <link rel="stylesheet" href="~/css/Admin/time_work.css">
</head>
<body class="body" style="display: flex;">
    <!-- sidebar -->
    <nav class="sidebar">
        <div class="logo">
            <a href=""><img src="~/img/logo.png" alt=""></a>
        </div>
        <ul id="sidebar_menu" class="metismenu">
            <li>
                <a href="@Url.Action("Index", "Dashboard")" style="background-color: var(--light-color);width: 215px;"><span><i class="fa-solid fa-house"></i>Thống kê</span></a>
            </li>
            <li>
                <a href="@Url.Action("Index", "ListOrder")"><span><i class="fa-solid fa-list-ul"></i>Danh sách đơn hàng</span></a>
            </li>

            <button class="toggleButton" onclick="order_Menu()"><span style="font-size: 16px; color: var(--grey-color);"><i class="fa-regular fa-folder"></i>Tạo đơn</span></button>

            <ul class="menu">
                <li><a href="@Url.Action("Index", "CreateOrder")"><span><i class="fa-regular fa-file-lines"></i>Đơn lẻ</span></a></li>
                <li><a href="@Url.Action("Index", "CreateGoods")"><span><i class="fa-regular fa-file-excel"></i>Đơn hàng loạt</span></a></li>
            </ul>
            <li>
                <a href="@Url.Action("Index", "Confirm")"><span><i class="fa-regular fa-folder-closed"></i>Xác nhận đơn hàng</span></a>
            </li>
            <button class="toggleButton" onclick="staff_Menu()"><span style="font-size: 16px; color: var(--grey-color);"><i class="fa-regular fa-folder"></i>Nhân viên</span></button>

            <ul class="staff">
                <li><a href="@Url.Action("Index", "Staff")"><span><i class="fa-regular fa-file-lines"></i>Thông tin cá nhân</span></a></li>
                <li><a href="@Url.Action("Index", "TimeWork")"><span><i class="fa-regular fa-file-excel"></i>Ca làm việc</span></a></li>
            </ul>

        </ul>
    </nav>
    <nav class="main">
        <div class="nav-bar">
            <div class="infor">
                <div class="avt">
                    <a href=""><img src="~/img/avt.jpg" alt=""></a>
                </div>
                <div class="name">
                    <span>Nguyệt</span>
                </div>
                <div class="log-out">
                    <div id="myLogout" class="logout-content">
                        <a href="#" onclick="return confirmLogout()"><span>Đăng xuất </span><i class="fa-solid fa-right-from-bracket" style="color: var(--turquoise-color);"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="creat_time">
            <span class="create_today">Tạo ca lấy hôm nay</span>
            <hr>
            <form action="/TimeWork/CreateShift" method="post">

                <div class="infor_time">
                    <div class="shift shift_name">
                        <label>Nhân viên</label>

                        <select name="staffId" id="size3" required>
                            @foreach (var staff in ViewBag.staffs)

                            {
                                <option value="@staff.Id">@(staff.Id.ToString() + " - " + staff.Name + " (" + staff.Email + " - " + staff.PhoneNumber + ") ")</option>
                            }
                        </select>
             
                </div>
               
                <div class="shift shift_shift">
                    <label>Ca</label>
                   
                        <select name="timeRange">
                            <option value="morning">Buổi sáng (7:00 - 11:00)</option>
                            <option value="afternoon">Buổi chiều (12:00 - 17:00)</option>
                            <option value="evening">Buổi tối (18:00 - 22:00)</option>
                        </select>


                    </div>
                    <div class="create_shift">
                        <input type="submit" value="Tạo ca">
                    </div>
                </div>

                @if (TempData["ErrorMessage"] != null)
                {
                    <span style="color:red">@TempData["ErrorMessage"]</span>
                }

			</form>
            
           

           



        </div>
        <div class="list_time">
            <span class="create_today">Danh sách ca lấy</span>
            <hr>
            <table>
                <tr>
                    <th style="width: 200px;text-align: left;">Mã ca</th>
                    <th style="text-align: left;">Shipper</th>
                    <th>Số điện thoại</th>
                    <th>Ngày</th>
                    <th>Ca</th>
                    <th> </th>
                </tr>
				@if (Model.Count != 0){

                    foreach (var shift in Model)
                    {
                        <tr>
                            <td>@shift.Id</td>
                            <td>@shift.Employee.Name</td>
                            <td>@shift.Employee.PhoneNumber</td>
                            <td>@shift.Day.ToString()</td>
                            <td>@(shift.TimeStart.ToString() + " - " + shift.TimeEnd.ToString())</td>
                            <td style="text-align: center">
                                <form action="/TimeWork/DeleteShift" method="post">
									<button type="submit" name="id" value=@shift.Id><i class="fa-solid fa-trash-can"></i></button>
								</form>
                            </td>
                        </tr>
                    }
				}
                           

            </table>
        </div>
        <script src="~/js/sidebar.js"></script>
</body>
</html>