FreightMana/Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;

namespace FreightMana.Controllers
{
    public class AboutUsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FreightMana/Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Mvc;

namespace FreightMana.Controllers
{
    public class ContactUsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FreightMana/Controllers/OurServiceController.cs
using Microsoft.AspNetCore.Mvc;

namespace FreightMana.Controllers
{
    public class OurServiceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FreightMana/Controllers/PriceController.cs
using Microsoft.AspNetCore.Mvc;

namespace FreightMana.Controllers
{
    public class PriceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FreightMana/Views/OurService/Index.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="~/img/fevicon.png" type="">
    <title> FINANCE | OUR SERVICES </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="~/css/base.css">
    <link rel="stylesheet" href="~/css/Customer/nab_bar.css">
    <link rel="stylesheet" href="~/css/Customer/our_services.css">
    <link rel="stylesheet" href="~/css/Customer/footer.css">

</head>

<body class="sub_page">

    <div class="hero_area">
        <header class="header_section">
            <div class="header_top">
            </div>
            <div class="header_bottom">
                <div class="container-fluid">
                    <nav class="navbar navbar-expand-lg custom_nav-container ">
                        <div class="logo"><img src="~/img/logo.png" alt=""></div>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ">
                                <li class="nav-item active">
                                    <a class="nav-link" href="/Home">Trang chủ<span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/OurService" style="color: var(--turquoise-color);">Dịch vụ</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/AboutUs">Về chúng tôi</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/Price">Giá cả</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/ContactUs">Liên hệ</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/LoginCustomer"><i class="fa-solid fa-user"></i><span style="margin-left: 5px;"> Đăng nhập</span></a>
                                </li>
                                <form class="form-inline">
                                    <a href="Home#searchForm">
                                        <button class="btn nav_search-btn" type="button"> <i class="fa fa-search" aria-hidden="true"></i></button>
                                    </a>
                                </form>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
    </div>
    </header>
    </div>


    <section class="service_section layout_padding">
        <div class="service_container">
            <div class="container ">
                <div class="heading_container">
                    <h2>
                        <span>Dịch vụ</span> của chúng tôi
                    </h2>
                    <p>
                        Hãy tin tưởng để chúng tôi giải quyết mọi nhu cầu vận chuyển của bạn
                    </p>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="box ">
                            <div class="img-box">
                                <img src="~/img/s1.png" alt="">
                            </div>
                            <div class="detail-box">
                                <h5>
                                    Vận tải hàng không
                                </h5>
                                <p>
                                    Tốc độ nhanh gấp 40 lần các phương tiện khác, đảm bảo độ an toàn, di chuyển dễ dàng, tránh gây vỡ hoặc biến dạng hàng hóa.
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 ">
                        <div class="box ">
                            <div class="img-box">
                                <img src="~/img/s2.png" alt="">
                            </div>
                            <div class="detail-box">
                                <h5>
                                    VẬN CHUYỂN ĐƯỜNG THỦY
                                </h5>
                                <p>
                                    Khả năng giao thông tốt, chuyên chở các loại hàng hóa có khối lượng lớn, tuyến đường vận chuyển thoải mái, thông thoáng.
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 ">
                        <div class="box ">
                            <div class="img-box">
                                <img src="~/img/s3.png" alt="">
                            </div>
                            <div class="detail-box">
                                <h5>
                                    XE TẢI VẬN CHUYỂN
                                </h5>
                                <p>
                                    Thời gian vận chuyển linh hoạt, lộ trình tiện lợn. Quy trình vận chuyển đơn giản, phương tiện đa dạng, hiệu quả kinh tế cao.
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 ">
                        <div class="box ">
                            <div class="img-box">
                                <img src="~/img/s4.png" alt="">
                            </div>
                            <div class="detail-box">
                                <h5>
                                    TÀU HỎA VẬN CHUYỂN
                                </h5>
                                <p>
                                    Cước giá thấp, vận chuyển hàng hóa lớn và khối lượng lớn, phù hợp cho việc vận chuyển hàng hóa quy mô lớn và số lượng lớn.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="info_section layout_padding2">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 info_col">
                    <div class="info_contact">
                        <h4>Địa chỉ</h4>
                        <div class="contact_link_box">
                            <a href=""><i class="fa fa-map-marker" aria-hidden="true"></i><span>Yên Nghĩa, Hà Đông, Hà Nội</span></a>
                            <a href=""><i class="fa fa-phone" aria-hidden="true"></i><span>Call +84 123456789</span></a>
                            <a href=""><i class="fa fa-envelope" aria-hidden="true"></i><span>finance@gmail.com</span></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 info_col">
                    <div class="info_detail">
                        <h4>Thông tin</h4>
                        <p>Dịch vụ vận chuyển hàng hóa của chúng tôi được tạo ra dành riêng cho các doanh nghiệp vừa và nhỏ đang tìm kiếm cách để nâng cao hiệu suất hoạt động của mình.</p>
                    </div>
                </div>
                <div class="col-lg-2 mx-auto info_col">
                    <div class="info_link_box">
                        <h4>Trang</h4>
                        <div class="info_links">
                            <a class="active" href="@Url.Action("Index", "Home")">Trang chủ</a>
                            <a class="" href="@Url.Action("Index", "OurService")">Dịch vụ</a>
                            <a class="" href="@Url.Action("Index", "AboutUs")">Về chúng tôi</a>
                            <a class="" href="@Url.Action("Index", "Price")">Giá cả</a>
                            <a class="" href="@Url.Action("Index", "ContactUs")">Liên hệ</a>
                        </div>
                    </div>
                </div>
                <div class=" col-lg-3 info_col ">
                    <h4>Đăng ký</h4>
                    <form>
                        <input type="text" placeholder="Nhập email" />
                       <a href="LoginCustomer"> <button type="submit">Đăng ký</button></a>
                    </form>
                </div>
            </div>
        </div>
    </section>
</body>
</html>